### ISSUE TITLE
Refazer repositório

### ISSUE THREAD

**Issue by Anderson-Juhasc** [btcbrdev/QuemAceitaBitcoin#4]
Amanhã fico de fazer o esquema do deploy. Peço que faço o backup dos branch `dev`

**Comment by paladini** [comment]
Resolvido! Fiz backup do branch dev :)

**Comment by Anderson-Juhasc** [comment]
Não deletou e refez o repositorio?

**Comment by paladini** [comment]
Nope, só fiz o backup do branch dev

**Comment by Anderson-Juhasc** [comment]
(y)
